CREATE SEQUENCE SEQ_Persona_id START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 1;

CREATE TABLE PERSONA
(
   ID                   DOUBLE         DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_Persona_id) NOT NULL,
   NOMBRE               VARCHAR(60)    NOT NULL,
   PAPELLIDO            VARCHAR(60)    NOT NULL,
   SAPELLIDO            VARCHAR(60),
   IDTIPOIDENTIFICADOR  VARCHAR(4)     NOT NULL,
   IDENTIFICADOR        VARCHAR(20)    NOT NULL,
   DIRECCION            VARCHAR(150)   NOT NULL,
   CODPOSTAL            DECIMAL(5)     NOT NULL,
   LOCALIDAD            VARCHAR(70)    NOT NULL,
   PROVINCIA            VARCHAR(70)    NOT NULL,
   TELEFONO             DECIMAL(15),
   TELMOVIL             DECIMAL(15)    NOT NULL
);

ALTER TABLE PERSONA
   ADD CONSTRAINT PK_PERSONA
   PRIMARY KEY (ID);

CREATE UNIQUE INDEX UK_PERSONA
   ON PERSONA (ID ASC);

CREATE UNIQUE INDEX UK_PERSONA_IDENTIF
   ON PERSONA (IDTIPOIDENTIFICADOR ASC, IDENTIFICADOR ASC);


COMMENT ON COLUMN PERSONA.ID IS 'identificador único';
COMMENT ON COLUMN PERSONA.NOMBRE IS 'Nombre de la persona';
COMMENT ON COLUMN PERSONA.PAPELLIDO IS 'primer apellido de la persona';
COMMENT ON COLUMN PERSONA.SAPELLIDO IS 'segundo apellido de la persona';
COMMENT ON COLUMN PERSONA.IDTIPOIDENTIFICADOR IS 'Tipo de documento identificador';
COMMENT ON COLUMN PERSONA.IDENTIFICADOR IS 'Número de documento identificador';
COMMENT ON COLUMN PERSONA.DIRECCION IS 'Dirección postal';
COMMENT ON COLUMN PERSONA.CODPOSTAL IS 'Código postal';
COMMENT ON COLUMN PERSONA.LOCALIDAD IS 'Localidad';
COMMENT ON COLUMN PERSONA.PROVINCIA IS 'Provincia';
COMMENT ON COLUMN PERSONA.TELEFONO IS 'Teléfono';
COMMENT ON COLUMN PERSONA.TELMOVIL IS 'Teléfono móvil';

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('José Luis','Bachiller', 'Gil' ,'NIF', '16801610H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('José Luis1','Bachiller1', 'Gil1' ,'NIF', '00000000H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Abogado1','Abogado1', 'Abogado1' ,'NIF', '00000001H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Abogado2','Abogado2', 'Abogado2' ,'NIF', '00000002H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Abogado3','Abogado3', 'Abogado1' ,'NIF', '00000003H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Persona1','Persona1', 'Persona1' ,'NIF', '00000004H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Persona2','Persona2', 'Persona2' ,'NIF', '00000005H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Persona3','Persona3', 'Persona3' ,'NIF', '00000006H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Persona4','Persona4', 'Persona4' ,'NIF', '00000007H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Procurador1','Procurador1', 'Procurador1' ,'NIF', '00000008H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Procurador2','Procurador2', 'Procurador2' ,'NIF', '00000009H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);

INSERT INTO PERSONA (NOMBRE, PAPELLIDO, SAPELLIDO, IDTIPOIDENTIFICADOR, IDENTIFICADOR, DIRECCION, CODPOSTAL, LOCALIDAD, PROVINCIA, TELEFONO, TELMOVIL) VALUES
('Procurador3','Procurador3', 'Procurador3' ,'NIF', '00000010H', 'Dirección postal', 42002, 'Alconaba', 'Soria', 975759137, 627393922);


CREATE TABLE USUARIO
(
   IDPERSONA   DOUBLE        NOT NULL,
   IDUSUARIO   VARCHAR(10)   NOT NULL,
   CONTRASENA  VARCHAR(10)   NOT NULL,
   IDPERFIL    VARCHAR(5)    NOT NULL
);

ALTER TABLE USUARIO
   ADD CONSTRAINT PK_USUARIO
   PRIMARY KEY (IDPERSONA);

CREATE INDEX CONSTRAINT_INDEX_2
   ON USUARIO (IDPERSONA ASC);

CREATE UNIQUE INDEX PK_USUARIO
   ON USUARIO (IDPERSONA ASC);


COMMENT ON COLUMN USUARIO.IDPERSONA IS 'Identificador de persona que puede conectarse';
COMMENT ON COLUMN USUARIO.IDUSUARIO IS 'Código de conexión del usuario';
COMMENT ON COLUMN USUARIO.CONTRASENA IS 'Contraseña del usuario';
COMMENT ON COLUMN USUARIO.IDPERFIL IS 'Codigo del perfil dentro de la aplicación';

-- BEGIN FOREIGN KEYS --
ALTER TABLE USUARIO
  ADD FOREIGN KEY (IDPERSONA)
  REFERENCES PERSONA (ID)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;
-- END FOREIGN KEYS --

Insert into usuario (IDPERSONA, IDUSUARIO, CONTRASENA, IDPERFIL) Select ID, 'ADMIN', 'ADMIN', 'ADMIN' from PERSONA where IDENTIFICADOR = '16801610H';

CREATE TABLE JUZGADO
(
   ID   			 DOUBLE        DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_Juzgado_id) NOT NULL,
   DESCRIPCION VARCHAR(100)  NOT NULL,
   IDTIPO    	 VARCHAR(15)    NOT NULL
);


CREATE SEQUENCE SEQ_Juzgado_id START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 1;

CREATE TABLE JUZGADO
(
   ID   			 DOUBLE        DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_Juzgado_id) NOT NULL,
   DESCRIPCION VARCHAR(100)  NOT NULL,
   IDTIPO    	 VARCHAR(15)    NOT NULL
);

COMMENT ON COLUMN JUZGADO.ID IS 'Identificador único del juzgado';
COMMENT ON COLUMN JUZGADO.DESCRIPCION IS 'Nombre del juzgado';
COMMENT ON COLUMN JUZGADO.IDTIPO IS 'Naturaleza del juzgado';

ALTER TABLE JUZGADO
   ADD CONSTRAINT PK_JUZGADO
   PRIMARY KEY (ID);
   
CREATE INDEX IX_JUZGADO
   ON JUZGADO (ID ASC);
   
CREATE UNIQUE INDEX UK_JUZGADO
   ON JUZGADO (DESCRIPCION ASC);
   
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('AUDIENCIA PROVINCIAL DE SORIA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('COMISARIA PROVINCIAL DE SORIA','ADMINISTRATIVO');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('FISCALIA DE MENORES Nº 1 DE SORIA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE INSTRUCCION Nº 1 DE ALMAZAN','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE INSTRUCCION Nº 1 DE EL BURGO DE OSMA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE INSTRUCCION Nº 1 DE SORIA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE INSTRUCCION Nº 2 DE SORIA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE INSTRUCCION Nº 3 DE SORIA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE INSTRUCCION Nº 4 DE SORIA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE LO CONTENCIOSO ADMINISTRATIVO Nº 1 DE SORIA','CONTENCIOSO');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE LO PENAL Nº 1 DE SORIA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE LO SOCIAL Nº 1 DE SORIA','SOCIAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE MENORES Nº 1 DE SORIA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE PAZ DE COVALEDA','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE PRIMERA INSTANCIA Nº 1 DE ALMAZAN','CIVIL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE PRIMERA INSTANCIA Nº 1 DE EL BURGO DE OSMA','CIVIL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE PRIMERA INSTANCIA Nº 1 DE SORIA','CIVIL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE PRIMERA INSTANCIA Nº 2 DE SORIA','CIVIL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE PRIMERA INSTANCIA Nº 3 DE SORIA','CIVIL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE PRIMERA INSTANCIA Nº 4 DE SORIA','CIVIL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DE VIGILANCIA PENITENCIARIA Nº 2 DE BURGOS','PENAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('JUZGADO DECANO','DECANO');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('TRIBUNAL SUPERIOR DE JUSTICIA DE CASTILLA Y LEÓN. SALA SOCIAL Nº 1 DE BURGOS','SOCIAL');
INSERT INTO JUZGADO (DESCRIPCION, IDTIPO ) VALUES
('COMISARIA PROVINCIAL DE SORIA','ADMINISTRATIVO');

CREATE TABLE ABOGADO
(
   IDPERSONA   	DOUBLE     NOT NULL,
   NUMCOLEG   	DOUBLE	   NOT NULL
);

ALTER TABLE ABOGADO
   ADD CONSTRAINT PK_ABOGADO
   PRIMARY KEY (IDPERSONA);

CREATE INDEX IX_ABOGADO
   ON ABOGADO (IDPERSONA ASC);

CREATE UNIQUE INDEX PK_ABOGADO
   ON ABOGADO (IDPERSONA ASC);
   
CREATE UNIQUE INDEX UK_ABOGADO
   ON ABOGADO (NUMCOLEG ASC);


COMMENT ON COLUMN ABOGADO.IDPERSONA IS 'Identificador con los datos de la persona';
COMMENT ON COLUMN ABOGADO.NUMCOLEG IS 'Numero de colegiado';

-- BEGIN FOREIGN KEYS --
ALTER TABLE ABOGADO
  ADD FOREIGN KEY (IDPERSONA)
  REFERENCES PERSONA (ID)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;
-- END FOREIGN KEYS --

Insert into ABOGADO (IDPERSONA, NUMCOLEG) Select ID, ID from PERSONA where NOMBRE like 'Abogado%';

CREATE TABLE PROCURADOR
(
   IDPERSONA   	DOUBLE     NOT NULL,
   NUMCOLEG   	DOUBLE	   NOT NULL
);

ALTER TABLE PROCURADOR
   ADD CONSTRAINT PK_PROCURADOR
   PRIMARY KEY (IDPERSONA);

CREATE INDEX IX_PROCURADOR
   ON PROCURADOR (IDPERSONA ASC);

CREATE UNIQUE INDEX PK_PROCURADOR
   ON PROCURADOR (IDPERSONA ASC);
   
CREATE UNIQUE INDEX UK_PROCURADOR
   ON PROCURADOR (NUMCOLEG ASC);


COMMENT ON COLUMN PROCURADOR.IDPERSONA IS 'Identificador con los datos de la persona';
COMMENT ON COLUMN PROCURADOR.NUMCOLEG IS 'Numero de colegiado';

-- BEGIN FOREIGN KEYS --
ALTER TABLE PROCURADOR
  ADD FOREIGN KEY (IDPERSONA)
  REFERENCES PERSONA (ID)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;
-- END FOREIGN KEYS --

Insert into PROCURADOR (IDPERSONA, NUMCOLEG) Select ID, ID from PERSONA where NOMBRE like 'Procurador%';

