CREATE SEQUENCE SEQ_TASUNTO_id START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 1;

CREATE TABLE TASUNTO
(
   ID   			 DOUBLE        DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_TASUNTO_id) NOT NULL,
   DESCRIPCION VARCHAR(100)  NOT NULL,
   IDTIPO    	 VARCHAR(15)   NOT NULL
);

COMMENT ON COLUMN TASUNTO.ID IS 'Identificador único de tipo de asunto';
COMMENT ON COLUMN TASUNTO.IDTIPO IS 'Naturaleza del juzgado, cada asunto puede ser de un tipo de los del juzgado ';
COMMENT ON COLUMN TASUNTO.DESCRIPCION IS 'Descripción del tipo de asunto';


ALTER TABLE TASUNTO
   ADD CONSTRAINT PK_TASUNTO
   PRIMARY KEY (ID);
   
CREATE INDEX IX_TASUNTO
   ON TASUNTO (ID ASC);
   
CREATE UNIQUE INDEX UK_TASUNTO
   ON TASUNTO (DESCRIPCION ASC);
